name: super-linter
on:push
jobs:
super-lint:
name: lint code base
runs-on:ubuntu-latest
steps:
-name: checkout mode
uses:actions/checkout@v2
-name: Run Super-Linter
uses:github/super-linter@v2
env:
DEFAULT_BRANCH: main
github-token: ${{secrets.token}}
